# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
      working-directory: /var/www/back-end/cycling_journey_nodejs
    - run: npm install pm2@latest -g #install pm2 global
    - run: pm2 -V #check pm2 version
    - run: pm2 list #check pm2 list
    #running pm2 in mode cluster and --watch set to auto restart if index.js have changes.
    - run: pm2 start "npm run unix_prod" --name Cycling_Journey --watch -i max
      working-directory: /var/www/back-end/cycling_journey_nodejs
      
